# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = ""

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://bosscha-test.github.io/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`.
copyright = "&copy; 2019 Observatorium Bosscha"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Enable comments by entering your Disqus shortname
disqusShortname = ""

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "academic"

# Get last modified date for content from Git?
enableGitInfo = true

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true

[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = false  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

# #########################################
# Atur urutan menu di halaman 'Tentang Kami'
# #########################################
[[menu.author-detil]]
  name = "Fasilitas"
  weight = 30
  identifier = "Fasilitas"

[[menu.staf]]
  name = "Staf"
  identifier = "staf"

[[menu.author-detil]]
  name = "Staf"
  url = "/../#people"
  weight = 20
  identifier = "staf"

[[menu.publikasi]]
  name = "Publikasi"
  identifier = "publikasi"

[[menu.penelitian]]
  name = "Publikasi"
  url = "/../#publications"
  weight = 20
  identifier = "publikasi"

#[[menu.repo]]
#  name = "Repository"
#  identifier = "repository"

#[[menu.Layanan]]
#  name = "Repository"
#  url = "/../#repository"
#  weight = 30
#  identifier = "repository"

#[[menu.material]]
#  name = "Material"
#  identifier = "material"

#[[menu.layanan]]
#  name = "Material"
#  identifier = "material"
#  url = "material"
#  weight = 20

#[[menu.penelitian]]
#  name = "Exoplanet"
#  url = "/../exo"
#  weight = 10
#  identifier = "exoplanet"

[permalinks]
    post = "/:year/:month/:day/:slug"