# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Beranda"
  url = "/"
  weight = 5

[[main]]
  name = "Berita"
  url = "#posts"
  weight = 20
  
[[main]]
  name = "Tentang Kami"
  url = "#about"
  weight = 10

[[main]]
  name = "Kunjungan"
  url = "/kunjungan/"
  weight = 30

[[main]]
  name = "Penelitian"
  url = "/penelitian/"
  weight = 30

[[main]]
  name = "Akademik"
  url = "/akademik/"
  weight = 40

[[main]]
  name = "Layanan"
  url = "/layanan/"
  weight = 50

[[main]]
  name = "Tautan"
  url = "#projects"
  weight = 60
# [[main]]
#   name = "Projects"
#   url = "#projects"
#   weight = 50

# [[main]]
#   name = "Publications"
#   identifier = "publikasi"
#   url = "#featured"
#   weight = 40

# [[main]]
#   name = "Publications-1"
#   parent = "publikasi"
#   url = "#featured"
#   weight = 10

[[main]]
  name = "Galeri"
  url = "/gallery/"
  # url = "/galeri-2/"
  weight = 70

[[main]]
  name = "Kontak"
  url = "/kontak/"
  weight = 80

# [[main]]
  # name = "Landing"
  # url = "/landing/"
  # weight = 90
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
